services:
  caddy:
    image: docker.io/caddy:2.10.0-alpine
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
      - '5678:5678'
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - n8n_network
    restart: unless-stopped

  n8n:
    image: docker.io/n8nio/n8n:1.102.0
    container_name: n8n
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_state:/home/node/.n8n_state
    networks:
      - n8n_network
    restart: unless-stopped

networks:
  n8n_network:
    driver: bridge

volumes:
  caddy_data:
  n8n_data:
  n8n_state:
