services:
  n8n:
    image: docker.io/n8nio/n8n:1.102.0
    container_name: n8n
    user: '1001:1001'
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/.n8n_state
    ports:
      - '127.0.0.1:5678:5678'
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_state:/home/node/.n8n_state
    networks:
      - n8n_network
    restart: unless-stopped

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
    driver: local
  n8n_state:
    driver: local
