#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/debian $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - unattended-upgrades
  - git

groups:
  - n8n

users:
  - name: admin
    groups: sudo, n8n
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: node
    system: true
    groups: n8n

write_files:
  - path: /etc/ssh/sshd_config.d/99-security.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      PubkeyAuthentication yes
      Protocol 2
      X11Forwarding no
      MaxAuthTries 3
      ClientAliveInterval 300
      ClientAliveCountMax 2

runcmd:
  # Clone repository and set correct permissions
  - |
    if [ ! -d /opt/apinasaari-slackbots ]; then
      mkdir -p /opt/apinasaari-slackbots
      chown admin:admin /opt/apinasaari-slackbots
      sudo -u admin git clone https://github.com/penny-five/apinasaari-slackbots.git /opt/apinasaari-slackbots
    fi
  # Create symlinks for config files
  - ln -sf /opt/apinasaari-slackbots/config/services/n8n.service /etc/systemd/system/n8n.service
  # Create folders for storing n8n state
  - sudo mkdir -p /opt/n8n/state
  - sudo chown -R root:n8n /opt/n8n/state
  - sudo chmod -R 775 /opt/n8n/state
  # Enable and restart services
  - systemctl daemon-reload
  - systemctl enable n8n
  - systemctl start n8n

final_message: 'Cloud-init finished successfully at $TIMESTAMP'
