name: deploy
on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '0.14.3'
      - uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          version: '311.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install package dependencies
        run: yarn install
      - name: Bootstrap project
        run: yarn bootstrap
      - name: Terraform init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME"
        working-directory: ./terraform
      - name: Terraform plan
        run: terraform plan -no-color -out plan.tfplan
        working-directory: ./terraform
      - name: Terraform apply
        run: terraform apply -no-color plan.tfplan
        working-directory: ./terraform
    env:
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_slack_token: ${{ secrets.SLACK_TOKEN }}
      TF_VAR_youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
      TF_VAR_ence_pelaa_slackbot_channel_id: ${{ secrets.ENCE_PELAA_SLACKBOT_CHANNEL_ID }}
      TF_VAR_game_pass_slackbot_channel_id: ${{ secrets.GAME_PASS_SLACKBOT_CHANNEL_ID }}
      TF_VAR_gofore_slackbot_channel_id: ${{ secrets.GOFORE_SLACKBOT_CHANNEL_ID }}
      TF_VAR_niilo22_slackbot_channel_id: ${{ secrets.NIILO22_SLACKBOT_CHANNEL_ID }}
      TF_VAR_solita_slackbot_channel_id: ${{ secrets.SOLITA_SLACKBOT_CHANNEL_ID }}
      TF_VAR_sotaraportti_slackbot_channel_id: ${{ secrets.SOTARAPORTTI_SLACKBOT_CHANNEL_ID }}
      TF_VAR_meme_generator_slackbot_slack_token: ${{ secrets.MEME_GENERATOR_SLACKBOT_SLACK_TOKEN }}
      TF_VAR_meme_generator_slackbot_slack_signing_secret: ${{ secrets.MEME_GENERATOR_SLACKBOT_SLACK_SIGNING_SECRET }}
